services:
  app:
    build:
      context: .
      network: host
    dns:
      - 10.0.136.7
    ports:
      - "8000:8000"
    environment:
      CORS_ORIGINS: "http://localhost:5173,http://127.0.0.1:5173"
